name: configure-dockerhub
description: Configure docker login
runs:
  using: composite
  steps:
    - name: Configure Docker Hub
      run: |-
        [ -z "$DOCKERHUB_USERNAME" ] && exit 0
        [ -z "$DOCKERHUB_TOKEN" ] && exit 0
        echo "${DOCKERHUB_TOKEN}" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      shell: bash
